### ISSUE TITLE
Toggle OBS Source Visibility don't show sources into group

### ISSUE THREAD

**Issue by Bronmaiky** [ebiggz/firebot-script-obs-control#15]
I have a group with 2 sources, option toggle OBS source visibility only show de group and not the sub-sources.
Is it possible show too this sub-sources?

**Comment by SwooshyCueb** [comment]
Any progress on this?

**Comment by ebiggz** [comment]
There were limitations to websocket v4 that caused this. Now that Firebots built in obs integration supports websocket v5, we can revisit this. I've moved this issue over to the Firebot repo. https://github.com/crowbartools/Firebot/issues/1927
