### ISSUE TITLE
No compatible with OBS 28

### ISSUE THREAD

**Issue by Bronmaiky** [ebiggz/firebot-script-obs-control#23]
OBS 28 uptaded with websocket v5.

**Comment by zunderscore** [comment]
Latest code in source is compatible with OBS Websocket v5. There just hasn't been a release yet because testing isn't complete.

**Comment by ebiggz** [comment]
As of v5.54.0, Firebot now has a built in OBS integration that supports websocket v5. This script is no longer needed.
